### ISSUE TITLE
Create Android-Demo in Kotlin 

### ISSUE THREAD

**Issue by KelvnPere** [cloudinary/android-demo#2]
Hi @nitzanj would love to contribute to cloudinary mobile projects? And would like to create a sample Demo for Kotlin. If that is something needed.

**Comment by shirlymanor** [comment]
@KelvnPere sure, we would love to have a sample code from the Community. Please share your code with us at support@cloudinary.com or here :)

**Comment by KelvnPere** [comment]
Nice @shirlymanor
